apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::777408466993:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1K6DTJUPNDXNI
      username: system:node:{{EC2PrivateDNSName}}
      rolearn: arn:aws:iam::777408466993:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-24T09:52:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "859"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 1d941a05-6db5-11ea-bfc5-06cfacd7f57a
