apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::541860086302:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1STJU3MOQ5XC1
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::541860086302:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-27T13:49:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "841"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c040d5b7-7031-11ea-8451-0e70ed5b2228
